language: python
python:
  - 2.7_with_system_site_packages
  - '3.5.1'
  - pypy
cache:
  directories:
    - $HOME/.cache/pip
sudo: false
matrix:
  fast_finish: true
  allow_failures:
    - python: '3.5.1'
    - python: pypy
env:
  - INTEGRATION_TEST=1
  - UNIT_TEST=1
addons:
  apt:
    packages:
    - libcurl4-openssl-dev
    - python-numpy
    - python-opencv
    - libimage-exiftool-perl
    - libopencv-dev
    - libjpeg-progs
    - libjpeg-dev
    - libpng-dev
    - libx264-dev
    - libass-dev
    - libvpx1
    - libvpx-dev
    - libwebp-dev
    - webp
    - gifsicle
    - python-numpy
    - python-scipy
    - libcairo2-dev
    - gfortran
    - libopenblas-dev
    - liblapack-dev
    - python-pyexiv2
    - yasm
install:
  - pip install -U pip
  - pip install --upgrade pip
  - cd $TRAVIS_BUILD_DIR && make setup
  - pip install coveralls
  - pip install cairosvg
  - wget https://ffmpeg.org/releases/ffmpeg-3.2.4.tar.xz
    -O /tmp/ffmpeg-3.2.4.tar.xz
  - mkdir /tmp/ffmpeg-source
  - tar -C /tmp/ffmpeg-source --strip 1 -xvf /tmp/ffmpeg-3.2.4.tar.xz
  - cd /tmp/ffmpeg-source && ./configure --prefix=/tmp --enable-gpl --enable-libx264 --enable-libvpx
  - cd /tmp/ffmpeg-source && make
  - cd /tmp/ffmpeg-source && make install
  - export PATH=/tmp/bin:$PATH
  - ffmpeg -version
before_script:
  - cd $TRAVIS_BUILD_DIR && make redis
script:
  make compile_ext ci_test
notifications:
  slack:
    secure: Sf6TJa/H3mq+RGqpLwKNRpNw0YQKX3+5bt5e37CSs8rOC+SoFHVNr29QhbXFPwmqQuy9qKb0t5rzChDIIvXErywU2lEw3/JlQtCt1xLsoUfpBF8g8ldoy6ESO2j9Jj6Y/M/4RN2zN3AAd5gfXPrdLHa++eiRaiAXXU+9ZvtUxuc=
after_success:
  coveralls
