version: 2.1

orbs:
  python: circleci/python@1.2

workflows:
  ci:
      jobs:
        - build-and-test-python36
        - build-and-test-python37
        - build-and-test-python38
        - build-and-test-python39

jobs:
  build-and-test-python36:
    working_directory: /app
    docker:
      - image: thumbororg/thumbor-test:36
    steps:
      - checkout
      - run:
          name: Update dependencies
          command: make setup
      - run:
          name: Compile Extensions
          command: make compile_ext
      - run:
          name: Redis
          command: make redis
      - run:
          name: Run Unit Tests
          command: make sequential-unit
      - store_test_results: # Upload test results for display in Test Summary: https://circleci.com/docs/2.0/collect-test-data/
          path: test-results
      - store_artifacts: # Upload test summary for display in Artifacts: https://circleci.com/docs/2.0/artifacts/
          path: test-results
          destination: tr1
      - run:
          name: Run Integration Tests
          command: env ASYNC_TEST_TIMEOUT=30 make integration_run
      - run:
          name: Lint
          command: make flake pylint
      - run:
          name: Coverage
          command: env COVERALLS_REPO_TOKEN=$COVERALLS_REPO_TOKEN coveralls

  build-and-test-python37:
    working_directory: /app
    docker:
      - image: thumbororg/thumbor-test:37
    steps:
      - checkout
      - run:
          name: Update dependencies
          command: make setup
      - run:
          name: Compile Extensions
          command: make compile_ext
      - run:
          name: Redis
          command: make redis
      - run:
          name: Run Unit Tests
          command: make sequential-unit
      - store_test_results: # Upload test results for display in Test Summary: https://circleci.com/docs/2.0/collect-test-data/
          path: test-results
      - store_artifacts: # Upload test summary for display in Artifacts: https://circleci.com/docs/2.0/artifacts/
          path: test-results
          destination: tr1
      - run:
          name: Run Integration Tests
          command: env ASYNC_TEST_TIMEOUT=30 make integration_run
      - run:
          name: Lint
          command: make flake pylint
      - run:
          name: Coverage
          command: env COVERALLS_REPO_TOKEN=$COVERALLS_REPO_TOKEN coveralls

  build-and-test-python38:
    working_directory: /app
    docker:
      - image: thumbororg/thumbor-test:38
    steps:
      - checkout
      - run:
          name: Update dependencies
          command: make setup
      - run:
          name: Compile Extensions
          command: make compile_ext
      - run:
          name: Redis
          command: make redis
      - run:
          name: Run Unit Tests
          command: make sequential-unit
      - store_test_results: # Upload test results for display in Test Summary: https://circleci.com/docs/2.0/collect-test-data/
          path: test-results
      - store_artifacts: # Upload test summary for display in Artifacts: https://circleci.com/docs/2.0/artifacts/
          path: test-results
          destination: tr1
      - run:
          name: Run Integration Tests
          command: env ASYNC_TEST_TIMEOUT=30 make integration_run
      - run:
          name: Lint
          command: make flake pylint
      - run:
          name: Coverage
          command: env COVERALLS_REPO_TOKEN=$COVERALLS_REPO_TOKEN coveralls

  build-and-test-python39:
    working_directory: /app
    docker:
      - image: thumbororg/thumbor-test:39
    steps:
      - checkout
      - run:
          name: Update dependencies
          command: make setup
      - run:
          name: Compile Extensions
          command: make compile_ext
      - run:
          name: Redis
          command: make redis
      - run:
          name: Run Unit Tests
          command: make sequential-unit
      - store_test_results: # Upload test results for display in Test Summary: https://circleci.com/docs/2.0/collect-test-data/
          path: test-results
      - store_artifacts: # Upload test summary for display in Artifacts: https://circleci.com/docs/2.0/artifacts/
          path: test-results
          destination: tr1
      - run:
          name: Run Integration Tests
          command: env ASYNC_TEST_TIMEOUT=30 make integration_run
      - run:
          name: Lint
          command: make flake pylint
      - run:
          name: Coverage
          command: env COVERALLS_REPO_TOKEN=$COVERALLS_REPO_TOKEN coveralls
