name: build
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        image-tag:
          - 37
          - 38
          - 39
          - 310
    steps:
      - uses: satackey/action-docker-layer-caching@v0.0.11
        continue-on-error: true
        with:
          key: thumbor-docker-${{ matrix.image-tag }}-{hash}
          restore-keys: |
            thumbor-docker-${{ matrix.image-tag }}-
      - uses: actions/checkout@v2
      - name: Build test image
        run: docker build -t test_image -f TestDockerfile${{ matrix.image-tag }} .
      - name: Create pip cache folder
        run: |
          mkdir -p ~/.cache/pip
      - name: Cache pip
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ matrix.image-tag }}-${{ hashFiles('**/setup.py') }}
          restore-keys: |
            ${{ runner.os }}-pip-${{ matrix.image-tag }}-
      - name: Start test container
        run: |
          docker run -dt --name thumbor_test -v $(pwd):/app -v ~/.cache/pip:/root/.cache/pip test_image
      - name: Change cache folder permission
        run: |
          docker exec thumbor_test -u 1001 chown -R 0:0 /root/.cache/pip
      - name: Fire up Redis
        run: docker exec thumbor_test make redis
      - name: Setup
        run: docker exec thumbor_test make setup
      - name: Compile Extensions
        run: docker exec thumbor_test make compile_ext
      - name: Run Unit Tests
        run: docker exec thumbor_test make sequential-unit
      - name: Run Integration Tests
        run: docker exec -e ASYNC_TEST_TIMEOUT=30 thumbor_test make integration_run
      - name: Lint
        run: docker exec thumbor_test make flake pylint
      - name: Generate lcov
        run: docker exec thumbor_test coverage lcov
      - name: Coveralls
        uses: coverallsapp/github-action@1.1.3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: coverage.lcov
          flag-name: run-${{ matrix.image-tag }}
          parallel: true
  finish:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Coveralls Finished
      uses: coverallsapp/github-action@1.1.3
      with:
        github-token: ${{ secrets.github_token }}
        parallel-finished: true
